매트랩에 익숙해서인지 Numpy도 매우 자연스럽게 쓰고있었다. 열심히한건 도움이 될 때가 있다.

### Concatenate - array 붙이기 

In [14]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
np.array([1,2,3,4,5])
np.arange(1,6,1)
np.vstack((a,b))  #concatenate
np.hstack((a,b))

array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

### Shape 가지고놀기 

In [42]:
a=np.zeros([4,5])
a.shape
a.ndim
a.size
a.nbytes
a.dtype
np.ones_like(np.zeros([4,5]))  #Input의 shape을 그대로 따라한다.

(4, 5)

2

20

160

dtype('float64')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Slicing하기 

In [24]:
a=np.arange(1,21,step=1).reshape([4,5])
print(a)
a[:,::2]   # x:y:z에서 x는 시작 index y는 끝 index, z는 step을 가르킨다.
a[::3,0:5:2]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 13, 15],
       [16, 18, 20]])

array([[ 1,  3,  5],
       [16, 18, 20]])

In [56]:
a=np.arange(1,11,1)
a
a[a>5]  #Boolean indexing
np.where(a>3)
a[np.where(a>3)] #Fancy indexing
a.take([1,4,7])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([ 6,  7,  8,  9, 10])

(array([3, 4, 5, 6, 7, 8, 9], dtype=int64),)

array([ 4,  5,  6,  7,  8,  9, 10])

array([2, 5, 8])

### reshape 생각해보기 

In [34]:
a=np.arange(1,25,step=1)
a.reshape([2,12])
a.reshape([2,3,4])
b=a.reshape([2,3,4])
b[0,0,0]
b[0,0,3]
#a의 각 elements는 앞에서부터 차례대로 b의 가장 깊은 곳부터 채운다.

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

1

4

### Comparison

In [44]:
a=np.array([1.1,np.NaN,np.Infinity])
np.isnan(a)
np.isinf(a)

array([False,  True, False])

array([False, False,  True])

In [48]:
a=np.arange(1,11,2)
a
np.where(a>5)

array([1, 3, 5, 7, 9])

(array([3, 4], dtype=int64),)